/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);


/*!
 * @brief 
 *
 */
void WDOG_B(void);


/*!
 * @brief 
 *
 */
void qspiFlash(void);


/*!
 * @brief 
 *
 */
void SDRAM(void);

/* GPIO_SD_B0_03 (coord K1), D1 */
#define SD_D1_PERIPHERAL                                                  USDHC1   /*!< Device name: USDHC1 */
#define SD_D1_SIGNAL                                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define SD_D1_CHANNEL                                                         1U   /*!< USDHC1 usdhc_data channel: 1 */

/* GPIO_SD_B0_02 (coord J1), D0 */
#define SD_D0_PERIPHERAL                                                  USDHC1   /*!< Device name: USDHC1 */
#define SD_D0_SIGNAL                                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define SD_D0_CHANNEL                                                         0U   /*!< USDHC1 usdhc_data channel: 0 */

/* GPIO_SD_B0_01 (coord J3), CLK */
#define SD_CLK_PERIPHERAL                                                 USDHC1   /*!< Device name: USDHC1 */
#define SD_CLK_SIGNAL                                                  usdhc_clk   /*!< USDHC1 signal: usdhc_clk */

/* GPIO_SD_B0_00 (coord J4), CMD */
#define SD_CMD_PERIPHERAL                                                 USDHC1   /*!< Device name: USDHC1 */
#define SD_CMD_SIGNAL                                                  usdhc_cmd   /*!< USDHC1 signal: usdhc_cmd */

/* GPIO_SD_B0_04 (coord H2), D2 */
#define SD_D2_PERIPHERAL                                                  USDHC1   /*!< Device name: USDHC1 */
#define SD_D2_SIGNAL                                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define SD_D2_CHANNEL                                                         2U   /*!< USDHC1 usdhc_data channel: 2 */

/* GPIO_SD_B0_05 (coord J2), D3 */
#define SD_D3_PERIPHERAL                                                  USDHC1   /*!< Device name: USDHC1 */
#define SD_D3_SIGNAL                                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define SD_D3_CHANNEL                                                         3U   /*!< USDHC1 usdhc_data channel: 3 */

/* GPIO_B1_12 (coord D13), CD */
#define SD_CD_GPIO                                                         GPIO2   /*!< GPIO device name: GPIO2 */
#define SD_CD_PORT                                                         GPIO2   /*!< PORT device name: GPIO2 */
#define SD_CD_PIN                                                            28U   /*!< GPIO2 pin index: 28 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SD(void);

/* WAKEUP (coord L6), WEKAUP */
#define XSNVS_WAKEUP_GPIO                                                  GPIO5   /*!< GPIO device name: GPIO5 */
#define XSNVS_WAKEUP_PORT                                                  GPIO5   /*!< PORT device name: GPIO5 */
#define XSNVS_WAKEUP_PIN                                                      0U   /*!< GPIO5 pin index: 0 */

/* PMIC_STBY_REQ (coord L7), 74LV245_OE_B */
#define XSNVS_PMIC_STBY_GPIO                                               GPIO5   /*!< GPIO device name: GPIO5 */
#define XSNVS_PMIC_STBY_PORT                                               GPIO5   /*!< PORT device name: GPIO5 */
#define XSNVS_PMIC_STBY_PIN                                                   2U   /*!< GPIO5 pin index: 2 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void xSNVS(void);

/* GPIO_AD_B1_11 (coord J13), ZZF_DATA06 */
#define __CAMERA_CSI_DATA06_PERIPHERAL                                       CSI   /*!< Device name: CSI */
#define __CAMERA_CSI_DATA06_SIGNAL                                      csi_data   /*!< CSI signal: csi_data */
#define __CAMERA_CSI_DATA06_CHANNEL                                           6U   /*!< CSI csi_data channel: 06 */

/* GPIO_AD_B1_04 (coord L12), ZZF_CLK */
#define __CAMERA_CSI_PIXCLK_PERIPHERAL                                       CSI   /*!< Device name: CSI */
#define __CAMERA_CSI_PIXCLK_SIGNAL                                    csi_pixclk   /*!< CSI signal: csi_pixclk */

/* GPIO_AD_B1_10 (coord L13), ZZF_DATA07 */
#define __CAMERA_CSI_DATA07_PERIPHERAL                                       CSI   /*!< Device name: CSI */
#define __CAMERA_CSI_DATA07_SIGNAL                                      csi_data   /*!< CSI signal: csi_data */
#define __CAMERA_CSI_DATA07_CHANNEL                                           7U   /*!< CSI csi_data channel: 07 */

/* GPIO_AD_B1_09 (coord M13), ZZF_DATA08 */
#define __CAMERA_CSI_DATA08_PERIPHERAL                                       CSI   /*!< Device name: CSI */
#define __CAMERA_CSI_DATA08_SIGNAL                                      csi_data   /*!< CSI signal: csi_data */
#define __CAMERA_CSI_DATA08_CHANNEL                                           8U   /*!< CSI csi_data channel: 08 */

/* GPIO_AD_B1_08 (coord H13), ZZF_DATA09 */
#define __CAMERA_CSI_DATA09_PERIPHERAL                                       CSI   /*!< Device name: CSI */
#define __CAMERA_CSI_DATA09_SIGNAL                                      csi_data   /*!< CSI signal: csi_data */
#define __CAMERA_CSI_DATA09_CHANNEL                                           9U   /*!< CSI csi_data channel: 09 */

/* GPIO_AD_B1_07 (coord K10), ZZF_HSYNC */
#define __CAMERA_CSI_HSYNC_PERIPHERAL                                        CSI   /*!< Device name: CSI */
#define __CAMERA_CSI_HSYNC_SIGNAL                                      csi_hsync   /*!< CSI signal: csi_hsync */

/* GPIO_AD_B1_06 (coord J12), ZZF_VSYNC */
#define __CAMERA_CSI_VSYNC_PERIPHERAL                                        CSI   /*!< Device name: CSI */
#define __CAMERA_CSI_VSYNC_SIGNAL                                      csi_vsync   /*!< CSI signal: csi_vsync */

/* GPIO_AD_B1_12 (coord H12), ZZF_DATA05 */
#define __CAMERA_CSI_DATA05_PERIPHERAL                                       CSI   /*!< Device name: CSI */
#define __CAMERA_CSI_DATA05_SIGNAL                                      csi_data   /*!< CSI signal: csi_data */
#define __CAMERA_CSI_DATA05_CHANNEL                                           5U   /*!< CSI csi_data channel: 05 */

/* GPIO_AD_B1_13 (coord H11), ZZF_DATA04 */
#define __CAMERA_CSI_DATA04_PERIPHERAL                                       CSI   /*!< Device name: CSI */
#define __CAMERA_CSI_DATA04_SIGNAL                                      csi_data   /*!< CSI signal: csi_data */
#define __CAMERA_CSI_DATA04_CHANNEL                                           4U   /*!< CSI csi_data channel: 04 */

/* GPIO_AD_B1_14 (coord G12), ZZF_DATA03 */
#define __CAMERA_CSI_DATA03_PERIPHERAL                                       CSI   /*!< Device name: CSI */
#define __CAMERA_CSI_DATA03_SIGNAL                                      csi_data   /*!< CSI signal: csi_data */
#define __CAMERA_CSI_DATA03_CHANNEL                                           3U   /*!< CSI csi_data channel: 03 */

/* GPIO_AD_B1_15 (coord J14), ZZF_DATA02 */
#define __CAMERA_CSI_DATA02_PERIPHERAL                                       CSI   /*!< Device name: CSI */
#define __CAMERA_CSI_DATA02_SIGNAL                                      csi_data   /*!< CSI signal: csi_data */
#define __CAMERA_CSI_DATA02_CHANNEL                                           2U   /*!< CSI csi_data channel: 02 */

/* GPIO_AD_B0_03 (coord G11), ZZF_TX */
#define __CAMERA_LPUART6_RX_PERIPHERAL                                   LPUART6   /*!< Device name: LPUART6 */
#define __CAMERA_LPUART6_RX_SIGNAL                                            RX   /*!< LPUART6 signal: RX */

/* GPIO_AD_B0_02 (coord M11), ZZF_RX */
#define __CAMERA_LPUART_TX_PERIPHERAL                                    LPUART6   /*!< Device name: LPUART6 */
#define __CAMERA_LPUART_TX_SIGNAL                                             TX   /*!< LPUART6 signal: TX */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void __camera(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SWD(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void ENC(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SPI(void);

/* GPIO_AD_B1_00 (coord J11), 陀螺仪_SCL */
#define AC_GYRO_IIC_SCL_GPIO                                               GPIO1   /*!< GPIO device name: GPIO1 */
#define AC_GYRO_IIC_SCL_PORT                                               GPIO1   /*!< PORT device name: GPIO1 */
#define AC_GYRO_IIC_SCL_PIN                                                  16U   /*!< GPIO1 pin index: 16 */

/* GPIO_AD_B1_01 (coord K11), 陀螺仪_SDA */
#define AC_GYRO_IIC_SDA_GPIO                                               GPIO1   /*!< GPIO device name: GPIO1 */
#define AC_GYRO_IIC_SDA_PORT                                               GPIO1   /*!< PORT device name: GPIO1 */
#define AC_GYRO_IIC_SDA_PIN                                                  17U   /*!< GPIO1 pin index: 17 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void AC_GYRO_IIC(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void GPIO(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void AC_UART(void);

/* GPIO_B0_15 (coord E11), OLED_RST */
#define AC_OLED_EST_GPIO                                                   GPIO2   /*!< GPIO device name: GPIO2 */
#define AC_OLED_EST_PORT                                                   GPIO2   /*!< PORT device name: GPIO2 */
#define AC_OLED_EST_PIN                                                      15U   /*!< GPIO2 pin index: 15 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void AC_OLED(void);

/* GPIO_B0_03 (coord D8), KEY_5D */
#define AC_KEY_5D_D3_GPIO                                                  GPIO2   /*!< GPIO device name: GPIO2 */
#define AC_KEY_5D_D3_PORT                                                  GPIO2   /*!< PORT device name: GPIO2 */
#define AC_KEY_5D_D3_PIN                                                      3U   /*!< GPIO2 pin index: 3 */

/* GPIO_B0_00 (coord D7), KEY_5D */
#define AC_KEY_5D_D0_GPIO                                                  GPIO2   /*!< GPIO device name: GPIO2 */
#define AC_KEY_5D_D0_PORT                                                  GPIO2   /*!< PORT device name: GPIO2 */
#define AC_KEY_5D_D0_PIN                                                      0U   /*!< GPIO2 pin index: 0 */

/* GPIO_B0_02 (coord E8), KEY_5D */
#define AC_KEY_5D_D2_GPIO                                                  GPIO2   /*!< GPIO device name: GPIO2 */
#define AC_KEY_5D_D2_PORT                                                  GPIO2   /*!< PORT device name: GPIO2 */
#define AC_KEY_5D_D2_PIN                                                      2U   /*!< GPIO2 pin index: 2 */

/* GPIO_B0_01 (coord E7), KEY_5D/上 */
#define AC_KEY_5D_D1_GPIO                                                  GPIO2   /*!< GPIO device name: GPIO2 */
#define AC_KEY_5D_D1_PORT                                                  GPIO2   /*!< PORT device name: GPIO2 */
#define AC_KEY_5D_D1_PIN                                                      1U   /*!< GPIO2 pin index: 1 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void AC_KEY_5D(void);

/* GPIO_B0_06 (coord A8), 后轮L */
#define AC_PWM_D6_PERIPHERAL                                                PWM2   /*!< Device name: PWM2 */
#define AC_PWM_D6_SIGNAL                                                       A   /*!< PWM2 signal: A */
#define AC_PWM_D6_CHANNEL                                                     0U   /*!< PWM2 A channel: 0 */

/* GPIO_B0_07 (coord A9), 后轮L */
#define AC_PWM_D7_PERIPHERAL                                                PWM2   /*!< Device name: PWM2 */
#define AC_PWM_D7_SIGNAL                                                       B   /*!< PWM2 signal: B */
#define AC_PWM_D7_CHANNEL                                                     0U   /*!< PWM2 B channel: 0 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void AC_PWM(void);

/* GPIO_B1_04 (coord E12), Buzz */
#define AC_BUZZ_BUZZ_GPIO                                                  GPIO2   /*!< GPIO device name: GPIO2 */
#define AC_BUZZ_BUZZ_PORT                                                  GPIO2   /*!< PORT device name: GPIO2 */
#define AC_BUZZ_BUZZ_PIN                                                     20U   /*!< GPIO2 pin index: 20 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void AC_Buzz(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
